#!/usr/bin/env python
"""Generate repo-local Method Wheel wrapper drafts for GitHub Spec Kit commands.

This script is intentionally repo-local and non-installing. It reads upstream
Spec Kit command templates and writes reviewable wrapper drafts under
`.ai/generated/spec-kit-hermes-adapter/`.

Safety invariants:
- does NOT write to ~/.hermes
- does NOT write to the active Hermes profile
- does NOT run `specify init --integration hermes`
- does NOT enable speckit-implement as a raw command
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = Path("C:/Users/Administrator/spec-kit-source")
DEFAULT_OUT = ROOT / ".ai" / "generated" / "spec-kit-hermes-adapter"

COMMAND_POLICY = {
    "specify": {
        "status": "enabled-draft",
        "port": "A",
        "guardrail": "WHAT/spec candidate only; do not choose technology stack.",
    },
    "clarify": {
        "status": "enabled-draft",
        "port": "A",
        "guardrail": "Ask only high-impact questions and write accepted answers back to durable spec.",
    },
    "checklist": {
        "status": "enabled-draft",
        "port": "A/E",
        "guardrail": "Check requirement/spec quality; do not implement.",
    },
    "plan": {
        "status": "enabled-draft",
        "port": "C",
        "guardrail": "Requires stable WHAT and accepted evidence/caveat state before HOW.",
    },
    "tasks": {
        "status": "enabled-draft",
        "port": "D-prep",
        "guardrail": "Produce bounded maker queue only; does not grant execution authority.",
    },
    "analyze": {
        "status": "enabled-draft",
        "port": "E",
        "guardrail": "Read-only cross-artifact checker; no mutation.",
    },
    "converge": {
        "status": "enabled-draft",
        "port": "E→D",
        "guardrail": "Append-only repair task generation after checker finding.",
    },
    "constitution": {
        "status": "gated-draft",
        "port": "F/A",
        "guardrail": "Governance/baseline command; owner/F approval required before use.",
    },
    "taskstoissues": {
        "status": "gated-draft",
        "port": "D/F",
        "guardrail": "GitHub side-effect handoff; requires repo/remote confirmation and owner approval.",
    },
    "implement": {
        "status": "disabled-handoff-only",
        "port": "D",
        "guardrail": "Do not expose as raw skill. Represent only as D-port handoff after A/B/C/E/F gates.",
    },
}

WRAPPER_HEADER = """---
name: speckit-{name}
description: Method Wheel wrapper draft for GitHub Spec Kit `{name}` command. Status: {status}. Port: {port}.
source: github/spec-kit/templates/commands/{name}.md
status: {status}
port: {port}
---

# speckit-{name} — Method Wheel Wrapper Draft

> Generated by `scripts/generate-spec-kit-hermes-adapter.py` for review only.  
> This file is **not installed** into Hermes and is **not enabled** as an active skill.

## Method Wheel Guardrails

```text
This is a Method Wheel wrapper around a GitHub Spec Kit command.
Do not execute it as a standalone linear workflow.
Respect A/B/B2/C/D/E/F routing.
If prerequisites are missing, stop and produce a blocker brief.
Do not write to ~/.hermes or the active Hermes profile from this wrapper.
```

- Wrapper status: `{status}`
- Method Wheel port: `{port}`
- Command guardrail: {guardrail}

"""

DISABLED_IMPLEMENT_NOTICE = """
## Disabled Raw Execution Notice

`speckit-implement` is intentionally generated as a handoff-only draft.

It may not be promoted as a raw active skill until a separate E/F review proves:

```text
1. A route is stable.
2. spec.md / plan.md / tasks.md exist.
3. E analyze passed or caveats were accepted.
4. allowed paths are bounded.
5. branch/worktree policy is defined.
6. risky or broad scope has owner approval.
```

Default action: convert to a bounded D-port handoff, not direct implementation.

"""


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def git_commit(path: Path) -> str | None:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(path), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        return out or None
    except Exception:
        return None


def extract_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    fm = text[4:end]
    meta: dict[str, str] = {}
    for line in fm.splitlines():
        if ":" in line and not line.startswith(" "):
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    return meta


def strip_yaml_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        return text
    end = text.find("\n---", 4)
    if end == -1:
        return text
    return text[end + 4 :].lstrip("\n")


def normalize_upstream_body(text: str) -> str:
    body = strip_yaml_frontmatter(text)
    # Keep upstream placeholders but make clear these are source-template terms.
    body = body.replace("__SPECKIT_COMMAND_", "__UPSTREAM_SPECKIT_COMMAND_")
    return body.rstrip() + "\n"


def generate_one(name: str, source_text: str) -> tuple[str, dict[str, object]]:
    policy = COMMAND_POLICY[name]
    frontmatter = extract_frontmatter(source_text)
    body = normalize_upstream_body(source_text)
    header = WRAPPER_HEADER.format(name=name, **policy)
    if name == "implement":
        header += DISABLED_IMPLEMENT_NOTICE
    content = (
        header
        + "## Upstream Command Metadata\n\n"
        + f"- Upstream description: {frontmatter.get('description', '(none)')}\n"
        + f"- Upstream template: `templates/commands/{name}.md`\n\n"
        + "## Upstream Command Body\n\n"
        + body
    )
    manifest = {
        "name": f"speckit-{name}",
        "command": name,
        "status": policy["status"],
        "port": policy["port"],
        "source_template": f"templates/commands/{name}.md",
        "source_sha256": sha256_text(source_text),
        "wrapper_sha256": sha256_text(content),
        "guardrail": policy["guardrail"],
        "promotable": policy["status"] != "disabled-handoff-only",
    }
    return content, manifest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    source_root = args.source
    commands_dir = source_root / "templates" / "commands"
    if not commands_dir.is_dir():
        raise SystemExit(f"missing Spec Kit commands dir: {commands_dir}")

    out_root = args.out
    wrappers_dir = out_root / "wrappers"
    wrappers_dir.mkdir(parents=True, exist_ok=True)

    generated: list[dict[str, object]] = []
    for name in sorted(COMMAND_POLICY):
        src = commands_dir / f"{name}.md"
        if not src.is_file():
            raise SystemExit(f"missing upstream template: {src}")
        source_text = src.read_text(encoding="utf-8")
        content, entry = generate_one(name, source_text)
        target = wrappers_dir / f"speckit-{name}.md"
        target.write_text(content, encoding="utf-8", newline="\n")
        entry["target_path"] = str(target.relative_to(ROOT)).replace("\\", "/")
        generated.append(entry)

    manifest = {
        "schema_version": 1,
        "generated_at_utc": "deterministic; regenerate from source_commit and command templates",
        "source_repo": "https://github.com/github/spec-kit",
        "source_path": str(source_root),
        "source_commit": git_commit(source_root),
        "target": "repo-local review drafts only",
        "writes_active_hermes_profile": False,
        "writes_default_hermes_home": False,
        "output_dir": str(out_root.relative_to(ROOT)).replace("\\", "/"),
        "commands": generated,
    }
    manifest_path = out_root / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")

    report_lines = [
        "# Spec Kit Hermes Adapter Generator Report",
        "",
        "> Generated repo-local wrapper drafts only. No Hermes profile writes were performed.",
        "",
        "## Source",
        "",
        f"- Source repo: https://github.com/github/spec-kit",
        f"- Source path: `{source_root}`",
        f"- Source commit: `{manifest['source_commit']}`",
        "",
        "## Safety Invariants",
        "",
        "- Does not run `specify init --integration hermes`.",
        "- Does not write `~/.hermes`.",
        "- Does not write the active `cangwei` profile.",
        "- Generates `speckit-implement` as `disabled-handoff-only`.",
        "",
        "## Generated Commands",
        "",
    ]
    for item in generated:
        report_lines.append(
            f"- `{item['name']}`: `{item['status']}` → `{item['port']}` — {item['guardrail']}"
        )
    report_lines += [
        "",
        "## Next E-Port Review",
        "",
        "Check wrapper guardrails, command policy, manifest, and generated diffs before any promotion.",
        "Initial promotion subset, if approved later: `speckit-specify`, `speckit-clarify`, `speckit-checklist`, `speckit-analyze`.",
    ]
    (out_root / "report.md").write_text("\n".join(report_lines) + "\n", encoding="utf-8", newline="\n")

    print(f"generated {len(generated)} wrappers under {out_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
